<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.5.1',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.0.2',
    ),
    'jetpack-backup-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-backup',
      'ver' => '4.0.6',
    ),
    'jetpack-blaze' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-blaze',
      'ver' => '0.25.4',
    ),
    'jetpack-boost-core' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-boost-core',
      'ver' => '0.3.3',
    ),
    'jetpack-boost-speed-score' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-boost-speed-score',
      'ver' => '0.4.0',
    ),
    'jetpack-classic-theme-helper' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-classic-theme-helper',
      'ver' => '0.8.2',
    ),
    'jetpack-compat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-compat',
      'ver' => '4.0.0',
    ),
    'jetpack-config' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-config',
      'ver' => '3.0.0',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '6.2.2',
    ),
    'jetpack-explat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-explat',
      'ver' => '0.2.3',
    ),
    'jetpack-forms' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-forms',
      'ver' => '0.34.5',
    ),
    'jetpack-image-cdn' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-image-cdn',
      'ver' => '0.7.2',
    ),
    'jetpack-import' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-import',
      'ver' => '0.9.2',
    ),
    'jetpack-ip' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-ip',
      'ver' => '0.4.1',
    ),
    'jetpack-jitm' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-jitm',
      'ver' => '4.0.3',
    ),
    'jetpack-licensing' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-licensing',
      'ver' => '3.0.2',
    ),
    'jetpack-masterbar' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-masterbar',
      'ver' => '0.10.5',
    ),
    'jetpack-my-jetpack' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-my-jetpack',
      'ver' => '5.3.0',
    ),
    'jetpack-password-checker' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-password-checker',
      'ver' => '0.4.1',
    ),
    'jetpack-plugins-installer' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-plugins-installer',
      'ver' => '0.5.0',
    ),
    'jetpack-post-list' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-post-list',
      'ver' => '0.7.2',
    ),
    'jetpack-protect-models' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-protect-models',
      'ver' => '0.4.1',
    ),
    'jetpack-protect-status' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-protect-status',
      'ver' => '0.4.1',
    ),
    'jetpack-publicize-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-publicize',
      'ver' => '0.57.1',
    ),
    'jetpack-search-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-search',
      'ver' => '0.47.5',
    ),
    'jetpack-stats' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-stats',
      'ver' => '0.15.0',
    ),
    'jetpack-stats-admin' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-stats-admin',
      'ver' => '0.24.0',
    ),
    'jetpack-sync' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-sync',
      'ver' => '4.2.0',
    ),
    'jetpack-videopress-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-videopress',
      'ver' => '0.25.6',
    ),
    'jetpack-waf' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-waf',
      'ver' => '0.23.1',
    ),
    'jetpack-wordads' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-wordads',
      'ver' => '0.4.5',
    ),
    'woocommerce-analytics' => array(
      'path' => 'jetpack_vendor/automattic/woocommerce-analytics',
      'ver' => '0.4.1',
    ),
  ),
);
