# yaml-language-server: $schema=https://coderabbit.ai/integrations/coderabbit-overrides.v2.json
language: "en"
chat:
    auto_reply: true
reviews:
    request_changes_workflow: true
    high_level_summary: true
    poem: false
    review_status: true
    collapse_walkthrough: true
    path_filters:
        - "!build/**"
    auto_review:
        enabled: true
        drafts: false
        base_branches:
            - "develop"
            - "add/.*"
            - "fix/.*"
            - "update/.*"
    path_instructions:
        - path: "**/*.{js,ts,tsx,jsx}"
          instructions: |
              "Perform a detailed review of the provided code with following key aspects in mind:
                - Review the code to ensure it is well-structured and adheres to best practices.
                - Verify compliance with WordPress coding standards.
                - Ensure the code is well-documented.
                - Check for security vulnerabilities and confirm the code is secure.
                - Optimize the code for performance, removing any unnecessary elements.
                - Validate JSDoc comments for accuracy, currency, and adherence to WordPress coding standards.
                - Ensure each line comment concludes with a period.
                - Confirm every JSDoc comment includes a @since tag indicating the next version of the plugin to include the code.
                - Guarantee compatibility with the latest version of WordPress, avoiding deprecated functions or features."
        - path: "**/*.{css,scss}"
          instructions: |
              "Perform a detailed review of the provided code with following key aspects in mind:
                - Review the SCSS code to ensure it is well-structured and adheres to best practices.
                - Convert dimensions greater than or equal to 3px to rem units using the to_rem function.
                - Utilize variables for sizes and colors defined in src/content-helper/common/css/variables.scss instead of hardcoding values."
        - path: "**/*.{html,php}"
          instructions: |
              "Perform a detailed review of the provided code with following key aspects in mind:
                - Review the HTML and PHP code to ensure it is well-structured and adheres to best practices.
                - Ensure the code follows WordPress coding standards and is well-documented.
                - Confirm the code is secure and free from vulnerabilities.
                - Optimize the code for performance, removing any unnecessary elements.
                - Validate comments for accuracy, currency, and adherence to WordPress coding standards.
                - Ensure each line comment concludes with a period.
                - Verify code compatibility with the latest version of WordPress, avoiding deprecated functions or features."
