language: php

services: mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - export PATH="$HOME/.config/composer/vendor/bin:$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then
      composer global require "phpunit/phpunit:^7"
    else
      composer global require "phpunit/phpunit:^5.4"
    fi
