configuration-version: 0.preview-unstable
slug: block-data-api
title: Block Data API
xdebug: true
mailhog: false
multisite: false
php: 8.0
wordpress: 6.2
mu-plugins: image
app-code: ../..
elasticsearch: false
phpmyadmin: false
