language: php

php:
    - "5.3"
    - "5.4"
    - "5.5"

env:
    - WP_VERSION=latest WP_MULTISITE=0

services:
    - elasticsearch

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - sleep 5 # ensure ES is running

script: phpunit
